-- Texas District Intelligence — role taxonomy reference data
--
-- Target:  Supabase project texas-esc-districts (fdnncloyxjsxwdhpfkjj)
-- Applies after 001_contact_layer.sql.
--
-- Seeded from the FULL role inventory profiled from the 2026-08-19 AskTED
-- exports on 2026-08-26: all 43 district roles and all 94 ESC roles present in
-- the files are mapped explicitly, so nothing falls through to 'other' by
-- accident. Re-runnable: both inserts upsert.
--
-- Business note worth carrying: library_media is flagged is_priority, but AskTED
-- has NO district-level library or media role at all — LIBRARY and MEDIA appear
-- only at ESC scope (22 rows each). An empty district library_media set means
-- the source does not carry that contact, NOT that a district has no librarian.
--
-- No BEGIN/COMMIT: the caller supplies the transaction.

insert into public.role_code_ref (role_code, label, seniority, is_priority) values
  ('superintendent', 'Superintendent', 1, true),
  ('assistant_superintendent', 'Assistant/Deputy/Associate Superintendent', 1, true),
  ('executive_director', 'Executive Director (ESC)', 1, true),
  ('principal', 'Campus Principal', 3, true),
  ('curriculum', 'Curriculum & Instruction', 2, true),
  ('library_media', 'Library / Media Services', 2, true),
  ('technology', 'Technology & Cybersecurity', 2, true),
  ('business_finance', 'Business / Finance', 2, false),
  ('special_education', 'Special Education', 2, false),
  ('assessment', 'Assessment & Accountability', 2, false),
  ('federal_programs', 'Federal Programs', 2, false),
  ('student_services', 'Student Services & Liaisons', 2, false),
  ('human_resources', 'Human Resources', 2, false),
  ('operations', 'Operations, Transport, Facilities', 2, false),
  ('safety', 'Safety, Security, Discipline', 2, false),
  ('data_reporting', 'Data / PEIMS / TREX Reporting', 2, false),
  ('board_member', 'Board Member / Officer', 9, false),
  ('admin_support', 'Administrative Support', 9, false),
  ('esc_program_staff', 'ESC Program / Instructional Staff', 9, false),
  ('other', 'Other / Unmapped', 9, false)
on conflict (role_code) do update set label = excluded.label, seniority = excluded.seniority, is_priority = excluded.is_priority;

insert into public.askted_role_map (source_scope, source_role, role_code) values
  ('district', 'ACCOUNTABILITY', 'assessment'),
  ('district', 'ACTING SUPERINTENDENT', 'superintendent'),
  ('district', 'AREA SUPERINTENDENT', 'assistant_superintendent'),
  ('district', 'ASSISTANT SUPERINTENDENT', 'assistant_superintendent'),
  ('district', 'ASSOCIATE SUPERINTENDENT', 'assistant_superintendent'),
  ('district', 'AT-RISK/DROPOUT PREVENTION', 'student_services'),
  ('district', 'ATHLETIC DIRECTOR', 'operations'),
  ('district', 'BILINGUAL/ESL', 'student_services'),
  ('district', 'BOARD ASSISTANT SECRETARY', 'board_member'),
  ('district', 'BOARD MEMBER', 'board_member'),
  ('district', 'BOARD PRESIDENT', 'board_member'),
  ('district', 'BOARD SECRETARY', 'board_member'),
  ('district', 'BOARD TREASURER', 'board_member'),
  ('district', 'BOARD VICE-PRESIDENT', 'board_member'),
  ('district', 'CFO/BUSINESS MANAGER', 'business_finance'),
  ('district', 'CHILD FIND CONTACT', 'special_education'),
  ('district', 'CURRICULUM', 'curriculum'),
  ('district', 'CYBERSECURITY COORDINATOR', 'technology'),
  ('district', 'DEPUTY SUPERINTENDENT', 'assistant_superintendent'),
  ('district', 'DYSLEXIA DESIGNEE', 'special_education'),
  ('district', 'ESSA/FEDERAL PROGRAMS', 'federal_programs'),
  ('district', 'EXECUTIVE DIRECTOR', 'executive_director'),
  ('district', 'FOSTER CARE LIAISON', 'student_services'),
  ('district', 'HOMELESS LIAISON', 'student_services'),
  ('district', 'HUMAN RESOURCES', 'human_resources'),
  ('district', 'INTERIM SUPERINTENDENT', 'superintendent'),
  ('district', 'PEIMS COORDINATOR', 'data_reporting'),
  ('district', 'POLICE CHIEF/HEAD OF SECURITY', 'safety'),
  ('district', 'PRINCIPAL', 'principal'),
  ('district', 'SAFE & SUPPORTIVE SCHOOLS PROG', 'safety'),
  ('district', 'SCHOOL IMPROVEMENT (DCSI)', 'assessment'),
  ('district', 'SCHOOL SOCIAL WORKER', 'student_services'),
  ('district', 'SECRETARY TO SUPERINTENDENT', 'admin_support'),
  ('district', 'SPECIAL EDUCATION DIRECTOR', 'special_education'),
  ('district', 'SUPERINTENDENT', 'superintendent'),
  ('district', 'TEACHER INCENTIVE ALLOTMENT', 'federal_programs'),
  ('district', 'TECHNOLOGY COORDINATOR', 'technology'),
  ('district', 'TED ADMINISTRATOR', 'data_reporting'),
  ('district', 'TEST COORDINATOR', 'assessment'),
  ('district', 'TRANSITION & EMPLOYMENT DSIGNE', 'special_education'),
  ('district', 'TRANSPORTATION', 'operations'),
  ('district', 'TREX COORDINATOR', 'data_reporting'),
  ('district', 'WEB ER CONTACT', 'data_reporting'),
  ('esc', 'ACCOUNTABILITY', 'assessment'),
  ('esc', 'ADULT EDUCATION (TxCHSE)', 'esc_program_staff'),
  ('esc', 'ALTERNATIVE CERTIFICATION', 'human_resources'),
  ('esc', 'ALTERNATIVE EDUCATION PROGRAM', 'esc_program_staff'),
  ('esc', 'ASSISTIVE TECHNOLOGY', 'special_education'),
  ('esc', 'AT-RISK/DROPOUT PREVENTION', 'student_services'),
  ('esc', 'AUTISM', 'special_education'),
  ('esc', 'BEHAVIOR / CLASSROOM MGMT', 'safety'),
  ('esc', 'BILINGUAL EDUCATION', 'esc_program_staff'),
  ('esc', 'BOARD CHAIR', 'board_member'),
  ('esc', 'BOARD MEMBER', 'board_member'),
  ('esc', 'BOARD SECRETARY', 'board_member'),
  ('esc', 'BOARD VICE CHAIR', 'board_member'),
  ('esc', 'BRAILLE SERVICES', 'special_education'),
  ('esc', 'BUS DRIVER TRAINING', 'operations'),
  ('esc', 'BUSINESS EDUCATION', 'esc_program_staff'),
  ('esc', 'CAREER & TECHNICAL EDUCATION', 'esc_program_staff'),
  ('esc', 'CHARTER SCHOOLS', 'esc_program_staff'),
  ('esc', 'CHIEF FINANCIAL OFFICER', 'business_finance'),
  ('esc', 'CHILD ABUSE', 'student_services'),
  ('esc', 'CHILD FIND', 'special_education'),
  ('esc', 'CHILD NUTRITION', 'operations'),
  ('esc', 'CO-OP PURCHASING', 'operations'),
  ('esc', 'CRCG', 'student_services'),
  ('esc', 'DATA PROCESSING/INFO MGMT', 'technology'),
  ('esc', 'DDV (Discipline Data)', 'data_reporting'),
  ('esc', 'DEAF EDUCATION', 'special_education'),
  ('esc', 'DISCIPLINE MANAGEMENT', 'safety'),
  ('esc', 'DYSLEXIA', 'special_education'),
  ('esc', 'EARLY CHILDHOOD EDUCATION', 'esc_program_staff'),
  ('esc', 'EDUCATIONAL ASSESSMENT', 'assessment'),
  ('esc', 'ELEMENTARY EDUCATION', 'esc_program_staff'),
  ('esc', 'EMERGENCY MANAGEMENT', 'safety'),
  ('esc', 'ESEA TITLE I MIGRANT', 'federal_programs'),
  ('esc', 'ESEA TITLE I STUDENT SUPPORT', 'federal_programs'),
  ('esc', 'EXECUTIVE DIRECTOR', 'executive_director'),
  ('esc', 'FACILITIES PLANNING', 'operations'),
  ('esc', 'FIELD SERVICE AGENT', 'esc_program_staff'),
  ('esc', 'FINE ARTS EDUCATION', 'esc_program_staff'),
  ('esc', 'FOREIGN LANGUAGES', 'esc_program_staff'),
  ('esc', 'FOSTER CARE LIAISON', 'student_services'),
  ('esc', 'GENERAL EDUCATION CURRICULUM', 'curriculum'),
  ('esc', 'GENERAL MANAGEMENT TRAINING', 'esc_program_staff'),
  ('esc', 'GIFTED AND TALENTED', 'esc_program_staff'),
  ('esc', 'GOVERNANCE', 'board_member'),
  ('esc', 'GRAPHICS LAB', 'esc_program_staff'),
  ('esc', 'GUIDANCE/COUNSELING', 'student_services'),
  ('esc', 'HEAD START', 'esc_program_staff'),
  ('esc', 'HIGH SCHOOL EDUCATION', 'esc_program_staff'),
  ('esc', 'HIV EDUCATION', 'esc_program_staff'),
  ('esc', 'HOMELESS LIAISON', 'student_services'),
  ('esc', 'INCLUSION', 'special_education'),
  ('esc', 'INSTRUCTIONAL TECHNOLOGY', 'technology'),
  ('esc', 'LANGUAGE ARTS', 'esc_program_staff'),
  ('esc', 'LESSON STUDY', 'esc_program_staff'),
  ('esc', 'LIBRARY', 'library_media'),
  ('esc', 'LRDV (Leaver Records)', 'data_reporting'),
  ('esc', 'MATH', 'esc_program_staff'),
  ('esc', 'MEDIA', 'library_media'),
  ('esc', 'MIDDLE SCHOOLS', 'esc_program_staff'),
  ('esc', 'NON-ED COMMUNITY BASED SERVICE', 'esc_program_staff'),
  ('esc', 'PARENT INVOLVEMENT', 'student_services'),
  ('esc', 'PEIMS COORDINATOR', 'data_reporting'),
  ('esc', 'PERSONNEL', 'human_resources'),
  ('esc', 'PRESCHOOL SPECIAL EDUCATION', 'special_education'),
  ('esc', 'READING', 'esc_program_staff'),
  ('esc', 'RESULTS DRIVEN ACCOUNTABILITY', 'assessment'),
  ('esc', 'SADV (Assessment Data)', 'data_reporting'),
  ('esc', 'SCHOOL BOARD MEMBER TRAINING', 'board_member'),
  ('esc', 'SCHOOL HEALTH', 'student_services'),
  ('esc', 'SCHOOL IMPROVEMENT SPECIALIST', 'assessment'),
  ('esc', 'SCHOOL SAFETY', 'safety'),
  ('esc', 'SCIENCE', 'esc_program_staff'),
  ('esc', 'SECRETARY TO EXEC DIRECTOR', 'admin_support'),
  ('esc', 'SOCIAL STUDIES', 'esc_program_staff'),
  ('esc', 'SPECIAL EDUCATION', 'special_education'),
  ('esc', 'STAFF DEVELOPMENT COORDINATOR', 'human_resources'),
  ('esc', 'TCLAS', 'federal_programs'),
  ('esc', 'TEACHER CERTIFICATION', 'human_resources'),
  ('esc', 'TEACHER INCENTIVE ALLOTMENT', 'federal_programs'),
  ('esc', 'TEACHER JOB PLACEMENT CENTER', 'human_resources'),
  ('esc', 'TEACHER OF THE YEAR COORD', 'esc_program_staff'),
  ('esc', 'TECHNOLOGY COORDINATOR', 'technology'),
  ('esc', 'TED ADMINISTRATOR', 'data_reporting'),
  ('esc', 'TEKS', 'curriculum'),
  ('esc', 'TEST COORDINATOR', 'assessment'),
  ('esc', 'TETN', 'data_reporting'),
  ('esc', 'THL (Texas Home Learning)', 'esc_program_staff'),
  ('esc', 'TREX COORDINATOR', 'data_reporting'),
  ('esc', 'VI ORIENTATION & MOBILITY', 'special_education'),
  ('esc', 'VISUALLY IMPAIRED', 'special_education'),
  ('esc', 'WAIVERS', 'federal_programs'),
  ('esc', 'WEB ER CONTACT', 'data_reporting'),
  ('esc', 'YEAR-ROUND EDUCATION', 'esc_program_staff')
on conflict (source_scope, source_role) do update set role_code = excluded.role_code;
